canonical: https://www.medizininformatik-initiative.de/fhir/core/
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
status: active
version: 2024.0.0
id: mii-ig-meta-de
name: MII_IG_Meta_DE
packageId: de.medizininformatikinitiative.kerndatensatz.meta
copyrightYear: 2019+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
#dependencies:
#  de.basisprofil.r4: 1.4.0
#  de.medizininformatikinitiative.kerndatensatz.meta: 1.0.3
