canonical: https://www.medizininformatik-initiative.de/fhir/modul-meta
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
status: active
version: 2025.0.0
id: mii-ig-meta-de
name: MII_IG_Meta_DE
packageId: de.medizininformatikinitiative.kerndatensatz.meta
copyrightYear: 2019+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
#dependencies:
#  hl7.fhir.uv.fhir-for-fair: 1.0.0
menu:
  Home: index.html
