canonical: https://www.medizininformatik-initiative.de/fhir/modul-meta
fhirVersion: 4.0.1
FSHOnly: false
applyExtensionMetadataToRoot: false
status: active
license: CC-BY-4.0
version: 2025.0.2
id: mii-ig-meta
name: MII_IG_Meta
title: "MII IG Meta"
description: Das Modul Meta enthält Basisartefakte für alle weiteren MII-IGs.
packageId: de.medizininformatikinitiative.kerndatensatz.meta
copyrightYear: 2019+
releaseLabel: ci-build
publisher:
  name: Medizininformatik Initiative
  url: https://www.medizininformatik-initiative.de/
#dependencies:
#  hl7.fhir.uv.fhir-for-fair: 1.0.0
menu:
  Home: index.html
  Artifacts: artifacts.html
