name: CI FHIR Validation

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
    secrets:
      SIMPLIFIER_USERNAME:
        required: true
      SIMPLIFIER_PASSWORD:
        required: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - name: Firely.Terminal (GitHub Actions)
        uses: FirelyTeam/firely-terminal-pipeline@v0.6.6
        with:
          PATH_TO_CONFORMANCE_RESOURCES: fsh-generated/resources
          PATH_TO_EXAMPLES: fsh-generated/resources
          PATH_TO_QUALITY_CONTROL_RULES: qc/custom
          DOTNET_VALIDATION_ENABLED: true
          JAVA_VALIDATION_ENABLED: true
          JAVA_VALIDATION_OPTIONS: -advisor-file advisor.json -resolution-context file:fsh-generated/resources/ -show-message-ids
          SIMPLIFIER_USERNAME: ${{ secrets.SIMPLIFIER_USERNAME }}
          SIMPLIFIER_PASSWORD: ${{ secrets.SIMPLIFIER_PASSWORD }}
          SUSHI_ENABLED: true 
          SUSHI_VERSION: 3.14.0
          JAVA_VALIDATOR_VERSION: 6.5.6
          EXPECTED_FAILS: VALIDATION_CONFORMANCE_DOTNET
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions Bot
          committer_email: ActionBot@github.com
          add: 'fsh-generated/resources/'
          message: auto-generated FHIR files by GitHub Actions (CI FSH to FHIR)