name: CI Search Param Tests

on:
  workflow_call:

jobs:
  search_param_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Search Param Bundle
        run: .github/workflows/search-param-test/create-search-param-bundle.sh
      - name: Run Blaze
        run: docker compose -f .github/workflows/search-param-test/blaze.yml up -d
      - name: Wait for Blaze
        run: .github/workflows/search-param-test/wait-for-url.sh http://localhost:8080/health
      - name: Load Data
        run: .github/workflows/search-param-test/load-data.sh
      - name: Test Search
        run: .github/workflows/search-param-test/test-search.sh