name: CI (FHIR Validation & SearchParameter Testing)

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  CI_FHIR_VALIDATION:
    uses: ./.github/workflows/ci_fhir_validation.yml
    with:
      ref: ${{ github.event.pull_request.head.ref }}

  CI_SEARCH_PARAM_TEST:
    uses: ./.github/workflows/ci_search_param_tests.yml
